### ISSUE TITLE
The Tandros research tree is not assigned to the Tandros ressources 

### ISSUE THREAD

**Issue by Hessi9** [Jasmarkelina/Tantros-Mod#18]
First of all I love this mod!!!
Unfortunately at the current version (Mindustry 140.3) the Trandros research tree is assigned to the Serpulo ressorces instead of the ressorces at Tandros. As it is impossible to produce the new ressources at Serpulo any research is impossible.

**Comment by Jasmarkelina** [comment]
Thanks! hmm... gonna try to fix that, maybe there's a problem w/the code or maybe the map

**Comment by Plastel** [comment]
Update to the newest version of the mod, it works now.

**Comment by Hessi9** [comment]
Now I get a crash when selecting Tandros:

Mindustry has crashed. How unfortunate.
Version: release build 140.3
OS: Windows 10 x64 (amd64)
Java Version: 15.0.1
Runtime Available Memory: 8164mb
Cores: 8
Mods: adc:15.0, advancements:1.0, erek:0.3, free-campaign:0.2, new-horizon:0.2.1, ol:0.5.1, tantros-mod:0.5, time-control:0.2, uaw:v0.8.3, exotic-mod:0.7 Alpha

java.lang.NullPointerException: Cannot read field "content" because "sec.preset.techNode.parent" is null
	at mindustry.ui.dialogs.PlanetDialog.renderProjections(PlanetDialog.java:512)
	at mindustry.graphics.g3d.PlanetRenderer.render(PlanetRenderer.java:122)
	at mindustry.ui.dialogs.PlanetDialog$5.draw(PlanetDialog.java:599)
	at arc.scene.Group.drawChildren(Group.java:125)
	at arc.scene.Group.draw(Group.java:51)
	at arc.scene.ui.layout.WidgetGroup.draw(WidgetGroup.java:142)
	at arc.scene.Group.drawChildren(Group.java:109)
	at arc.scene.ui.layout.Table.draw(Table.java:108)
	at arc.scene.ui.Dialog.draw(Dialog.java:297)
	at mindustry.ui.dialogs.PlanetDialog.draw(PlanetDialog.java:746)
	at arc.scene.Group.drawChildren(Group.java:125)
	at arc.scene.Group.draw(Group.java:51)
	at arc.scene.Scene.draw(Scene.java:137)
	at mindustry.core.UI.update(UI.java:149)
	at arc.ApplicationCore.update(ApplicationCore.java:37)
	at mindustry.ClientLauncher.update(ClientLauncher.java:230)
	at arc.backend.sdl.SdlApplication.listen(SdlApplication.java:204)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:192)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:54)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:39)

**Comment by Plastel** [comment]
i don't know to read this

**Comment by Hessi9** [comment]
From my Programming experience I guess is Java exceptions is caused by a Invalid name in a Technology entry (techNode.) of a script file discribing it's dependent parent technology (.parent).
As it is working at your system it may be just a uncomplete checkin to github.

**Comment by Hessi9** [comment]
Thanks a lot for the greate service. With the newest Version it works now like intended.

**Comment by Plastel** [comment]
No problem, with the player's help we can improve the mod or/and fix the bugs, thanks for your contribution!
