### ISSUE TITLE
I can't access campaign 

### ISSUE THREAD

**Issue by JustAnAverageUser69** [Jasmarkelina/Tantros-Mod#41]
I can't access campaign with this mod, simple
I should probably be more specific, my game always crash everytime I open campaign with this mod

**Comment by Samrox2004** [comment]
im having the same issue whenever i try to go into the campaign midustry crashes and gives me this error log

Mindustry has crashed. How unfortunate.
Version: steam build 145.1
OS: Windows 10 x64 (amd64)
Java Version: 16.0.1
Runtime Available Memory: 4078mb
Cores: 12
Mods: mi2-utilities-java:1.4.2c, tantros-mod:0.9.1, time-control:0.2

java.lang.NullPointerException: Cannot read field "content" because "sec.preset.techNode.parent" is null
	at mindustry.ui.dialogs.PlanetDialog.renderProjections(PlanetDialog.java:512)
	at mindustry.graphics.g3d.PlanetRenderer.render(PlanetRenderer.java:115)
	at mindustry.ui.dialogs.PlanetDialog$5.draw(PlanetDialog.java:599)
	at arc.scene.Group.drawChildren(Group.java:125)
	at arc.scene.Group.draw(Group.java:51)
	at arc.scene.ui.layout.WidgetGroup.draw(WidgetGroup.java:142)
	at arc.scene.Group.drawChildren(Group.java:109)
	at arc.scene.ui.layout.Table.draw(Table.java:108)
	at arc.scene.ui.Dialog.draw(Dialog.java:297)
	at mindustry.ui.dialogs.PlanetDialog.draw(PlanetDialog.java:759)
	at arc.scene.Group.drawChildren(Group.java:125)
	at arc.scene.Group.draw(Group.java:51)
	at arc.scene.Scene.draw(Scene.java:137)
	at mindustry.core.UI.update(UI.java:155)
	at arc.ApplicationCore.update(ApplicationCore.java:37)
	at mindustry.ClientLauncher.update(ClientLauncher.java:228)
	at arc.backend.sdl.SdlApplication.listen(SdlApplication.java:204)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:192)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:54)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:39)

**Comment by Plastel** [comment]
Hello, I'm the "secondary" developer of Tantros, Even though we've got this issue before and we fixed it.. it appeared again, We could try to fix it, but I'm sorry to inform that; Due to the lost of interest on mindustry of me and Jas, The mod is currently in a "coma" state and it's most likely that we won't make advances on it until a few months, Again, we're sorry...
